---
cluster.name: "docker-cluster"
network.host: 0.0.0.0
xpack.security.enabled: false
## X-Pack settings
## see https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-xpack.html
#
# xpack.license.self_generated.type: basic
# xpack.security.enabled: true
# xpack.monitoring.collection.enabled: true
